spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: postgres
  jmx:
    default-domain: ex-bbs-api
server:
  servlet:
    context-path: /ex-bbs-api